### ISSUE TITLE
Skill bonus due to backgrounds.

### ISSUE THREAD

**Issue by Mostlylost** [ZWinther/aime-module#5]
When creating the backgrounds from the book I figured out how to upgrade standard skills but I can not find the new ones for aime.  Is there a way to add/upgrade a proficiency introduced by the module?

**Comment by ZWinther** [comment]
Hey there, I'm not sure what you mean exactly. Backgrounds (as an item) can only give items as far as I can see.

If you can please elaborate, I'll take a look at it :)

**Comment by Mostlylost** [comment]
Sure. Thank you for your help. Here is a pictures.
![backgrounds](https://user-images.githubusercontent.com/5436651/221425504-992ca32f-80d6-499e-b1af-1fd8582f73dc.png)
I created a background and a background feature. In the background feature I can reference an Attribute Key and increase a proficiency but the ones for the AIME skills are not listed. I hope this helps I am learning FoundryVTT and DnD at the same time. LOL

**Comment by ZWinther** [comment]
Ahh I see. So this looks like an issue between my module and the [Dynamic Active Effects](https://gitlab.com/tposney/dae) module.

I honestly don't know if my custom skills are supposed to be there automatically (which is a bug on my end) or whether I'm supposed to add something to make it work with DAE.

I'll look into it, but it's probably going to be a little while, since it's not game breaking per se, but it is an important module (although the features are being added to the 5e system on the next big update), so I will definitely get to it soon.

**Comment by ZWinther** [comment]
Update: It does work, but you have to manually type the string like so:

![image](https://user-images.githubusercontent.com/82144909/221426951-d9137713-6e22-46c8-ac3d-129512ae05d9.png)

The shorthand for the skills are:

Lore = lor
Riddle = rid
Shadow-Lore = sha
Traditions = tra

**Comment by Mostlylost** [comment]
Awesome!!! Thank you.
